callapiurl:
  seal: 
    #创建椭圆印章
    createEllipseSeal: /seal/seal/front/createEllipseSeal
    #创建圆形印章
    createCircularSeal: /seal/seal/front/createCircularSeal
    #创建双行人名印章
    createDoubleRowSeal: /seal/seal/front/createDoubleRowSeal
    #创建单行人名印章
    createSingleRowSeal: /seal/seal/front/createSingleRowSeal
    #印章透明处理
    sealLimpid: /seal/seal/front/sealLimpid
  ####################文件服务#####################
  file:
    #上传文件
    upload: /fss/fss/upload
    uploadBase64: /fss/fss/uploadBase64
    #文件删除
    delete: /fss/fss/delete
    #文件下载
    download: /fss/fss/download
    downloadBase64: /fss/fss/downloadBase64
####################证书服务#####################
  cert: 
    #证书申请
    apply: /cs/cert/apply
    #证书查询
    get: /cs/cert/get
    #证书吊销
    revoke: /cs/cert/revoke
    #证书更新
    update: /cs/cert/update
##################签章验章######################
  dsvs: 
    #PDF签章
    sign: /dsvs/dsvs/sign
    #PDF批量签章
    batchSign:  /dsvs/dsvs/batchSign
    #PDF验章
    verifyBase64: /dsvs/dsvs/verifyBase64
##################文档生产服务######################
  dgs: 
    #PDF模板填充
    pdfFill: /dgs/dgs/pdfFill   
    #PDF创建
    pdfCreate: /dgs/dgs/pdfCreate