server:
  port: 8080
  tomcat:
    max-threads: 1000
    uriEncoding: utf-8
    max-http-post-size: 1024000000
  servlet:
    session:
      timeout: 7200
######  Start 配置注册中心  #######
    context-path:  / #这是配置项目名称
    context-parameters:
      slaveMode: 1
######  end 配置注册中心  #######

spring:
  jmx:
    default-domain: product
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  application:
    name: product
#######################证书信息######################################  
itrus:
  cert:
    oName: 天威诚信服务有限公司
    ouName: 天威诚信产品研发部
    raCode: #sm2-itrus
    validDays: 365 
    
    
http:
  # 1 或者 true 为采用http方式调用原子服务，其余均为callApi方式
  httped: 0
  #retryCount: 1 #3
  url: http://124.205.224.180:9339 #当 httped 不为1 或者 true ， 此配置无效，但必须保留 url: 可以不配置任何值
  alled: 0   # 1 或者 true 为原子服务合并版本方式
  
taskExecutor:
  coreSize: 10 #核心线程数 --线程池基本大小
  maxSize: 10 #最大线程数
  queueCapacity: 10 #线程队列容量
  keepAliveSeconds: 10000 #线程活跃时间
  threadName: task-concurrent-work #线程池名称
  waitForJobsToCompleteOnShutdown: true #所有任务结束后是否关闭线程池
  