spring:
  jmx:
    default-domain: product
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  application:
    name: common-product
  cloud:
    nacos:
      config:
        namespace: develop
        server-addr: 192.168.100.233:32105
        group: v1
        file-extension: yaml
        extension-configs[0]:
          group: v1
          data-id: common-product.yaml
      discovery:
        namespace: develop
        server-addr: 192.168.100.233:32105
        group: v1

logging:
  level:
    root: INFO
    com: INFO
    com.itrus.newportal.dao: debug    #mapper 路径 可以打印sql
  file: ./logs/${spring.application.name}.log
  file.max-size: 50MB
  file.max-history: 14
    
    
http:
  retryCount: 1 #3
  alled: 1   # 1 或者 true 为原子服务合并版本方式  0或false为拆分版原子服务方式
  uag: userapi #用户中心注册中心名称
  atomed: atom-sign-all #合并版原子服务注册中心名称
  fcs: fcs #文档转换服务 只有拆分版
  seal: seal #印章服务拆分版注册中心名称
  fss: fss #文件存储服务拆分版注册中心名称
  cs: cs #证书服务拆分版注册中心名称
  dsvs: dsvs #签章验章服务拆分版注册中心名称
  dgs: dgs #文档生成服务拆分版注册中心名称
  
taskExecutor:
  coreSize: 10 #核心线程数 --线程池基本大小
  maxSize: 10 #最大线程数
  queueCapacity: 10 #线程队列容量
  keepAliveSeconds: 10000 #线程活跃时间
  threadName: task-concurrent-work #线程池名称
  waitForJobsToCompleteOnShutdown: true #所有任务结束后是否关闭线程池
  